### ISSUE TITLE
ServerName instead of ip ?

### ISSUE THREAD

**Issue by MujtabaFR** [davidstoneham/react-native-mssql#12]
Hi,
I'm using **react-native-mssql** on react-native 0.59.10 on Android
I'm wondering if there is a way to connect to the mssql server using **ServerName** instead of the **ip**

I've tried to do so in the connection config but couldn't connect, while it works perfectly using ip address

The problem is that the ip address is changeable and I was not able to fix it.. while the ServerName is already fixed

Thanks in advance

**Comment by davidstoneham** [comment]
There shouldn't be an issue using the computer name instead of the IP as long as the server is on your local network. If you have issues with the server name then there will be a configuring issue that isn't resolving the computer name to it's address. Usually this will be a firewall or port issue on the server
