### ISSUE TITLE
Can I connect with windows authenticated server

### ISSUE THREAD

**Issue by Fire-Hound** [davidstoneham/react-native-mssql#6]
The user and password when connecting, leverages the sql server authentication. Is there a way to connect it to my sql server without this user and pass?

**Comment by davidstoneham** [comment]
Unfortunately not. Leveraging Windows authentication requires the connection to be made from a windows device. Since you would be using this plugin on android it wouldn't work anyway.

You can set up a username and password or you can try using your windows computer credentials but you will need to full resolve the username path

**Comment by Fire-Hound** [comment]
Thanks for the reply, appreciate your work!

**Comment by davidstoneham** [comment]
No problem at all!

**Comment by HZSamir** [comment]
I am actually facing the same issue, can you please elaborate on your answer with an example?
